### ISSUE TITLE
"Runtime.ImportModuleError: Error: Cannot find module '@libsql/linux-x64-gnu" when bundling with esbuild for aws lambda

### ISSUE THREAD

**Issue by MaazDev** [libsql/libsql-client-ts#112]
I was switching my database from planetscale to turso but I'm getting the following error 
```
 {
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module '@libsql/linux-x64-gnu'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module '@libsql/linux-x64-gnu'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)",
    "    at async start (file:///var/runtime/index.mjs:1256:23)",
    "    at async file:///var/runtime/index.mjs:1262:1"
  ]
}
```

I use the aws cdk to build and deploy my aws lambda function internally it uses esbuild here is a simple reproduction step

/nodejs/index.ts
```
import { drizzle } from 'drizzle-orm/libsql';
import { createClient } from '@libsql/client';
const client = createClient({ url: 'DATABASE_URL', authToken: 'DATABASE_AUTH_TOKEN' });

const db = drizzle(client);

export const handler = async (event) => {
  console.log('event', event);
}
```

the aws cdk code to deploy the function:
```
import {Construct} from 'constructs';
import {NodejsFunction} from 'aws-cdk-lib/aws-lambda-nodejs';
import {Architecture, Runtime} from 'aws-cdk-lib/aws-lambda';

export class SendUserToDynamo extends Construct {
  function: NodejsFunction;
  constructor(scope: Construct, id: string) {
    super(scope, id);

    // lambda function that triggers on aws lambda user created event
    this.function = new NodejsFunction(this, 'sendUserToDynamo', {
      entry: __dirname + '/nodejs/index.ts',
      handler: 'handler',
      architecture: Architecture.X86_64,
      runtime: Runtime.NODEJS_18_X,
    });
  }
}
```

everything works when I'm using the planetscale driver so the error must come from libsql and not the cdk build step, I tried using a dockerfile without typescript and so esbuild and it did worked

**Comment by hugotox** [comment]
Similar error happens when deploying to vercel. Any advice?

**Comment by raymclee** [comment]
same here
and confirmed downgrading to 0.3.2 fixed it

**Comment by raymclee** [comment]
0.3.3 also works

**Comment by ebacksys** [comment]
bump

**Comment by thomascgray** [comment]
Confirming I'm seeing this too, also switching from Planetscale to Turso.
Interestingly the error doesn't happen in local env, only when deployed to Netlify. Running node 16.
Pulling `@libsql/client` down to `0.3.2` from `0.5.3` fixed things for me.

**Comment by jschuur** [comment]
Ran into this too and got it working with 0.3.3.

**Comment by bchilcott** [comment]
Having the same issue, but I'm on Windows 11 and getting:
```
Cannot find module '@libsql/win32-x64-msvc'
```
Works with `0.3.3` for now, though.

**Comment by yspreen** [comment]
I'm experiencing this on an arm lambda: https://github.com/tursodatabase/libsql-js/issues/70

**Comment by yspreen** [comment]
Downgrading to 0.3.3 just results in "Cannot find module '@libsql/linux-arm64-gnu'"" too, no change

**Comment by jschuur** [comment]
I ended up using the web/HTTP client to be able to run the latest version:

```ts
import { createClient } from '@libsql/client/web';
```

**Comment by yspreen** [comment]
it does say in the docs that you should use it for vercel functions and the like. the docs could be a bit clearer here. nothing mentions what to use for lambda

**Comment by thescientist13** [comment]
Just wanted to chime in that I also ran into this exact same issue deploying to AWS Lambda using [Architect](https://arc.codes/docs/en/get-started/quickstart) and on version `0.6.0` of **@libsql/client**.  Including that it all worked fine locally.  (using the Architect's sandbox mode for local dev)

The [suggestion](https://github.com/tursodatabase/libsql-client-ts/issues/112) to use web worked for me.  👍

**Comment by patrickalima98** [comment]
The same problem here using versions 0.5.x and 0.6.x with Deno Deploy with NPM comparability layer. I tried to use it with esm.sh but I didn't have any success.

**Comment by dreamorosi** [comment]
If you want to use the native client that uses the `libsql` binary under the hood in Lambda, you'll have to build the function in a similar arch/environment or use a Lambda layer, also built under the same conditions (i.e. Docker).

A bundler like esbuild won't be able to include the correct version (i.e. `@libsql-linux-arm64-gnu`) unless it's itself running on that same hardware.

This worked for me:

```ts
import { Stack, type StackProps, CfnOutput } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Architecture, Code, LayerVersion, Runtime } from 'aws-cdk-lib/aws-lambda';
import { NodejsFunction, OutputFormat } from 'aws-cdk-lib/aws-lambda-nodejs';

export class LibsqlStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const libsqlLayer = new LayerVersion(this, 'LibsqlLayer', {
      compatibleArchitectures: [Architecture.ARM_64],
      compatibleRuntimes: [Runtime.NODEJS_20_X],
      code: Code.fromAsset('./layers/libsql/nodejs', {
        bundling: {
          image: Runtime.NODEJS_20_X.bundlingImage,
          environment: {
            npm_config_cache: "/tmp/npm_cache",
            npm_config_update_notifier: "false",
          },
          command: [
            'bash',
            '-xc',
            [
              'cd $(mktemp -d)',
              'cp /asset-input/package* .',
              'npm ci',
              'cp -r node_modules /asset-output/'
            ].join(' && '),
          ]
        }
      }),
    });

    const fn = new NodejsFunction(this, 'MyFunction', {
      runtime: Runtime.NODEJS_20_X,
      architecture: Architecture.ARM_64,
      entry: './src/index.ts',
      handler: 'handler',
      bundling: {
        minify: true,
        mainFields: ['module', 'main'],
        sourceMap: true,
        format: OutputFormat.ESM,
        externalModules: ['@libsql/client'],
      },
      layers: [libsqlLayer],
    });

    new CfnOutput(this, 'FunctionArn', {
      value: fn.functionArn,
    });
  }
}
```

then in my function I use `@libsql/client` as normal:

```ts
import { Logger } from "@aws-lambda-powertools/logger";
import { createClient } from "@libsql/client";

const logger = new Logger();
const db = createClient({
  url: "file:/tmp/sqlite.db",
});

export const handler = async () => {

  await db.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT)");

  await db.execute({ sql: "INSERT INTO users (name) VALUES (?)", args:  ["Alice"]});

  const rows = await db.execute("SELECT * FROM users");

  logger.info("Rows: ", {rows});

  return {
    statusCode: 200,
    body: JSON.stringify("Hello, World!"),
  };
};
```

which when invoked prints this:

```json
{
    "level": "INFO",
    "message": "Rows: ",
    "sampling_rate": 0,
    "service": "service_undefined",
    "timestamp": "2024-06-27T18:14:43.388Z",
    "xray_trace_id": "1-667dac12-2624c2867735f80f34586f58",
    "rows": {
        "columns": [
            "id",
            "name"
        ],
        "columnTypes": [
            "INTEGER",
            "TEXT"
        ],
        "rows": [
            [
                1,
                "Alice"
            ]
        ],
        "rowsAffected": 0,
        "lastInsertRowid": null
    }
}
```

The advantage of using a Lambda layer like that is that you can still continue using `esbuild` for the function(s) - the only caveat there is to make sure to specify `externalModules: ['@libsql/client'],` so that the dependency is not included in the bundle - this is because it comes from the Layer.

**Comment by NicoPowers** [comment]
> If you want to use the native client that uses the `libsql` binary under the hood in Lambda, you'll have to build the function in a similar arch/environment or use a Lambda layer, also built under the same conditions (i.e. Docker).
> 
> A bundler like esbuild won't be able to include the correct version (i.e. `@libsql-linux-arm64-gnu`) unless it's itself running on that same hardware.
> 
> This worked for me:
> 
> ```ts
> import { Stack, type StackProps, CfnOutput } from 'aws-cdk-lib';
> import { Construct } from 'constructs';
> import { Architecture, Code, LayerVersion, Runtime } from 'aws-cdk-lib/aws-lambda';
> import { NodejsFunction, OutputFormat } from 'aws-cdk-lib/aws-lambda-nodejs';
> 
> export class LibsqlStack extends Stack {
>   constructor(scope: Construct, id: string, props?: StackProps) {
>     super(scope, id, props);
> 
>     const libsqlLayer = new LayerVersion(this, 'LibsqlLayer', {
>       compatibleArchitectures: [Architecture.ARM_64],
>       compatibleRuntimes: [Runtime.NODEJS_20_X],
>       code: Code.fromAsset('./layers/libsql/nodejs', {
>         bundling: {
>           image: Runtime.NODEJS_20_X.bundlingImage,
>           environment: {
>             npm_config_cache: "/tmp/npm_cache",
>             npm_config_update_notifier: "false",
>           },
>           command: [
>             'bash',
>             '-xc',
>             [
>               'cd $(mktemp -d)',
>               'cp /asset-input/package* .',
>               'npm --prefix . i @libsql/client',
>               'cp -r node_modules /asset-output/'
>             ].join(' && '),
>           ]
>         }
>       }),
>     });
> 
>     const fn = new NodejsFunction(this, 'MyFunction', {
>       runtime: Runtime.NODEJS_20_X,
>       architecture: Architecture.ARM_64,
>       entry: './src/index.ts',
>       handler: 'handler',
>       bundling: {
>         minify: true,
>         mainFields: ['module', 'main'],
>         sourceMap: true,
>         format: OutputFormat.ESM,
>         externalModules: ['@libsql/client'],
>       },
>       layers: [libsqlLayer],
>     });
> 
>     new CfnOutput(this, 'FunctionArn', {
>       value: fn.functionArn,
>     });
>   }
> }
> ```
> 
> then in my function I use `@libsql/client` as normal:
> 
> ```ts
> import { Logger } from "@aws-lambda-powertools/logger";
> import { createClient } from "@libsql/client";
> 
> const logger = new Logger();
> const db = createClient({
>   url: "file:/tmp/sqlite.db",
> });
> 
> export const handler = async () => {
> 
>   await db.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT)");
> 
>   await db.execute({ sql: "INSERT INTO users (name) VALUES (?)", args:  ["Alice"]});
> 
>   const rows = await db.execute("SELECT * FROM users");
> 
>   logger.info("Rows: ", {rows});
> 
>   return {
>     statusCode: 200,
>     body: JSON.stringify("Hello, World!"),
>   };
> };
> ```
> 
> which when invoked prints this:
> 
> ```json
> {
>     "level": "INFO",
>     "message": "Rows: ",
>     "sampling_rate": 0,
>     "service": "service_undefined",
>     "timestamp": "2024-06-27T18:14:43.388Z",
>     "xray_trace_id": "1-667dac12-2624c2867735f80f34586f58",
>     "rows": {
>         "columns": [
>             "id",
>             "name"
>         ],
>         "columnTypes": [
>             "INTEGER",
>             "TEXT"
>         ],
>         "rows": [
>             [
>                 1,
>                 "Alice"
>             ]
>         ],
>         "rowsAffected": 0,
>         "lastInsertRowid": null
>     }
> }
> ```
> 
> The advantage of using a Lambda layer like that is that you can still continue using `esbuild` for the function(s) - the only caveat there is to make sure to specify `externalModules: ['@libsql/client'],` so that the dependency is not included in the bundle - this is because it comes from the Layer.

Hey @dreamorosi , thanks for this.

I am currently trying to get this to work with SST Ion that uses Pulumi under the hood, and it seems it won't bundle this automatically as CDK does.

How would I go about bundling this manually? Here you can see what Pulumi offers from an AWS lambda layer standpoint: https://www.pulumi.com/registry/packages/aws/api-docs/lambda/layerversion/#constructor-example

As you can see, there is no option to set the command or the bundling configuration. Same with the Lambda itself, as seen here: https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#constructor-example

**Comment by NicoPowers** [comment]
I was able to solve this by adding the `@libsql/client` as a nodejs dependency which allows SST to do an NPM install of them in the function bundle:
```
import { usersTable } from "./database";
import { TursoAuthToken, TursoDatabaseUrl } from "./database";

export const api = new sst.aws.Function("Api", {
  url: true,
  link: [usersTable, TursoAuthToken, TursoDatabaseUrl],
  handler: "./packages/functions/api/index.handler",
  architecture: "arm64",   
  nodejs: {
    install: ["@libsql/client"]
  }        
});
```

**Comment by robertseghedi** [comment]
> I ended up using the web/HTTP client to be able to run the latest version:
> 
> ```ts
> import { createClient } from '@libsql/client/web';
> ```

this works

**Comment by devtanna** [comment]
> > I ended up using the web/HTTP client to be able to run the latest version:
> > ```ts
> > import { createClient } from '@libsql/client/web';
> > ```
> 
> this works

This worked for me too! Thanks!

**Comment by kylesloper** [comment]
fyi this is still an active issue. `@libsql/client/web` is also not a feasible workaround as it doesn't support embedded replicas.

**Comment by mohammadazeemwani** [comment]
running into same issue here 
but not for serverless but for electron build in production 

target: arm64 dep, 

the error only shows in production not in development and is hard to debug 

so any help is welcome

**Comment by seantiz** [comment]
> running into same issue here but not for serverless but for electron build in production
> 
> target: arm64 dep,
> 
> the error only shows in production not in development and is hard to debug
> 
> so any help is welcome

Same, I got the local macOS binary to work fine but when pattern-matching to try and load the Linux Intel binary it doesn't resolve so I must be making a mistake somewhere. But without being able to load the plugin, then I cannot execute any logging to know where it is failing.

**Comment by gborobio73** [comment]
Running into this issue:
```
Error: Cannot find module '@libsql/linux-x64-gnu'
```
SvelteKit app running in Azure as s Static Web App.

Importing from `'@libsql/client/web'` solves the issue.

**Comment by brapifra** [comment]
This is my workaround to use libsql's native client while deploying with SST 3.x on a Macbook Pro M1.

1. `npm i @libsql/linux-x64-gnu`
2. Add this to your lambda in sst.config.ts:
```typescript
export const api = new sst.aws.Function("Api", {
     ...otherProperties,
      nodejs: {
        install: ["@libsql/client"],
        esbuild: {
          external: [
            "@libsql/client",
            "@libsql/darwin-arm64",
            "@libsql/linux-x64-gnu",
          ],
        },

        copyFiles: $dev
          ? undefined
          : [
              {
                from: `node_modules/@libsql/linux-x64-gnu/**/*`,
                to: `node_modules/@libsql/linux-x64-gnu/`,
              },
            ],
      },   
});

```

**Comment by Pulkit7070** [comment]
Opened a docs PR covering all the bundler scenarios for this: tursodatabase/turso-docs#385

  Covers the /web subpath fix for remote databases, esbuild --alias for transitive deps, and the CDK Lambda Layer approach for embedded replicas.
